repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: Go Format
        entry: bash -c 'gofmt -l -w .'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-vet
        name: Go Vet
        entry: bash -c 'go vet ./...'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-test
        name: Go Test
        entry: bash -c 'go test ./...'
        language: system
        files: '\.go$'
        pass_filenames: false

      - id: go-mod-tidy
        name: Go Mod Tidy
        entry: bash -c 'go mod tidy && git diff --exit-code go.mod go.sum'
        language: system
        pass_filenames: false

      - id: no-hardcoded-values
        name: Check hardcoded values
        entry: bash -c 'grep -r "localhost:[0-9]\+" --include="*.go" . && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: no-silent-errors
        name: Check silent error handling
        entry: bash -c 'grep -r "_ =" --include="*.go" . | grep -v "test" && exit 1 || exit 0'
        language: system
        pass_filenames: false

      - id: check-error-handling
        name: Check error handling
        entry: bash -c 'grep -r "if err != nil {[[:space:]]*}" --include="*.go" . && exit 1 || exit 0'
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint
        args: ['--timeout=5m']