version: '3.8'

services:
  claude-cache:
    build: .
    container_name: claude-cache-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DEBUG=false
      - CACHE_DIR=/app/cache
      - UPDATE_SCHEDULE=0 2 * * 0
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=claude-3-5-sonnet-20241022
      - ENABLE_ANALYTICS=true
    volumes:
      - ./cache:/app/cache
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - claude-network

  # Optional: Redis for distributed caching
  redis:
    image: redis:7-alpine
    container_name: claude-cache-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - claude-network

networks:
  claude-network:
    driver: bridge

volumes:
  redis-data: